import type { Product } from '@/src/types/product';

export const mockProducts: Product[] = [
  {
    id: '1',
    brand: 'Adidas',
    name: 'Adidas Stan Smith Gore-Tex Orange Limited (Kids)',
    sku: 'UH6907-612',
    sizeType: 'big kids',
    releaseDate: '2024-01-01',
    description: 'A limited kids version of the Adidas Stan Smith Gore-Tex with orange details.',
    imageUrl: null,
    eazyScore: 77,
    communityScore: 78,
    ratingCount: 24,
    lowestPrice: 120,
  },
  {
    id: '2',
    brand: 'Nike',
    name: 'Nike Dunk Low Retro White Black',
    sku: 'DD1391-100',
    sizeType: 'men',
    releaseDate: '2021-01-14',
    description: 'A classic black and white Nike Dunk Low colorway.',
    imageUrl: null,
    eazyScore: 84,
    communityScore: 81,
    ratingCount: 142,
    lowestPrice: 115,
  },
  {
    id: '3',
    brand: 'New Balance',
    name: 'New Balance 990v6 Grey',
    sku: 'M990GL6',
    sizeType: 'men',
    releaseDate: '2022-11-17',
    description: 'The sixth version of the 990 in the signature grey suede and mesh build.',
    imageUrl: null,
    eazyScore: 88,
    communityScore: 86,
    ratingCount: 97,
    lowestPrice: 199,
  },
  {
    id: '4',
    brand: 'Asics',
    name: 'Asics Gel-Kayano 14 White Midnight',
    sku: '1201A019-108',
    sizeType: 'men',
    releaseDate: '2023-03-10',
    description: 'A retro runner revival with layered mesh and metallic overlays.',
    imageUrl: null,
    eazyScore: 82,
    communityScore: 84,
    ratingCount: 61,
    lowestPrice: 150,
  },
  {
    id: '5',
    brand: 'Nike',
    name: 'Nike Air Force 1 Low White',
    sku: 'CW2288-111',
    sizeType: 'men',
    releaseDate: '2020-07-15',
    description: 'The all-white staple Air Force 1 Low.',
    imageUrl: null,
    eazyScore: 79,
    communityScore: 74,
    ratingCount: 305,
    lowestPrice: 110,
  },
  {
    id: '6',
    brand: 'Salomon',
    name: 'Salomon XT-6 Black Phantom',
    sku: 'L41086600',
    sizeType: 'unisex',
    releaseDate: '2022-05-01',
    description: 'A technical trail silhouette adopted as an everyday shoe.',
    imageUrl: null,
    eazyScore: 85,
    communityScore: null,
    ratingCount: 0,
    lowestPrice: 200,
  },
  {
    id: '7',
    brand: 'Adidas',
    name: 'Adidas Samba OG Cloud White Core Black',
    sku: 'B75806',
    sizeType: 'unisex',
    releaseDate: '2018-01-01',
    description: 'The classic Samba OG in white leather with black stripes.',
    imageUrl: null,
    eazyScore: 81,
    communityScore: 83,
    ratingCount: 218,
    lowestPrice: 100,
  },
  {
    id: '8',
    brand: 'Vans',
    name: 'Vans Old Skool Black White',
    sku: 'VN000D3HY28',
    sizeType: 'unisex',
    releaseDate: null,
    description: null,
    imageUrl: null,
    eazyScore: null,
    communityScore: 72,
    ratingCount: 88,
    lowestPrice: 70,
  },
];
